### PR TITLE
Improve Visibility of Homepage Slider Text

### PR DESCRIPTION
**Pull request by Soumojitshome2023**
Improve Visibility of Homepage Slider Text

## Before :
Screenshot (488)

## After: 
image

### CODE REVIEW

**Comment by Anushka-Bhowmick** [comment]
image

Here, make the "we always would be nascent" text just below the welcome text. It is not properly aligned

**Comment by Soumojitshome2023** [comment]
so what? This issue only for Homepage Slider not for Hero Section .

**Comment by Anushka-Bhowmick** [comment]
> so what? This issue only for Homepage Slider not for Hero Section .

you were assigned for the responsiveness issue yesterday #29. Since I closed it, please make the changes in this issue itself

**Comment by Soumojitshome2023** [comment]
# Okay ??

image

**Comment by Anushka-Bhowmick** [comment]
> # Okay ??
> image

cool!

**Pull request merged**
