### PR TITLE
Trying to Containerizes CODE using Docker

### PR DESCRIPTION
**Pull request by ANAMASGARD**
I want to say sorry but i really just didn't knew how to add the dark and light theme because there were react files and many things i could not wrap my head into so sorry for that .
I WANTED TO ADD A DOCKERFILE TO YOUR PROJECT PLEASE SEE IF IS IT CORRECT AND HOW CAN I CAN IT TO MAKE IT BETTER .
I AM JUST A BEGINNER TRYING TO LEARN NEW THINGS THIS IS ALSO MY FIRST PULL REQUEST ALSO .

### CODE REVIEW

**Comment by Anushka-Bhowmick** [comment]
> I want to say sorry but i really just didn't knew how to add the dark and light theme because there were react files and many things i could not wrap my head into so sorry for that .
> I WANTED TO ADD A DOCKERFILE TO YOUR PROJECT PLEASE SEE IF IS IT CORRECT AND HOW CAN I CAN IT TO MAKE IT BETTER .
> I AM JUST A BEGINNER TRYING TO LEARN NEW THINGS THIS IS ALSO MY FIRST PULL REQUEST ALSO .

As it is deployed on vercel, I'll have to build the dockerfile separately, so the deployment has failed. Otherwise, your code seems to be alright.

**Comment by ANAMASGARD** [comment]
Ma'am I wanted to ask that as a beginner can you please tell what resources
he should be following so that he is able to do open source contributions
to your project.

**Comment by Anushka-Bhowmick** [comment]
> Ma'am I wanted to ask that as a beginner can you please tell what resources he should be following so that he is able to do open source contributions to your project.

Please contact me on linkedIn. I'll connect with you there.

**Comment by Anushka-Bhowmick** [comment]
@ANAMASGARD i am not current looking for dockerize the project ... but thanks for your interest.

**Pull request closed without merging**
