### PR TITLE
Changes in the styling fixed

### PR DESCRIPTION
**Pull request by callmeVineeth**
Navbar hovering styles for medium screens  fixed by adding a media breakpoint at '992 px'.

### CODE REVIEW

**Comment by Anushka-Bhowmick** [comment]
> Navbar hovering styles for medium screens fixed by adding a media breakpoint at '992 px'.

make it for all screen sizes and on hovering make the text teal colored that has been used.

**Comment by Anushka-Bhowmick** [comment]
great! +10 points🎉

**Comment by Anushka-Bhowmick** [comment]
@callmeVineeth have you joined the discord server?

**Comment by callmeVineeth** [comment]
> @callmeVineeth have you joined the discord server?

No, can you provide the link

**Comment by Anushka-Bhowmick** [comment]
> > @callmeVineeth have you joined the discord server?
> 
> No, can you provide the link

https://discord.com/invite/7vypmaSETr

**Comment by callmeVineeth** [comment]
Hi I am unable to register in the program, since it is showing Registration closed. What to do ?

**Comment by Anushka-Bhowmick** [comment]
> Hi I am unable to register in the program, since it is showing Registration closed. What to do ?

wait! have you registered for Apertre as a mentee?

**Comment by callmeVineeth** [comment]
Are you taking about this,  
Screenshot (215)

**Comment by Anushka-Bhowmick** [comment]
> Are you taking about this, Screenshot (215)

I am asking if you know that this open source event is going on? Because we are assigning the issues to the participants.

**Comment by callmeVineeth** [comment]
No

**Comment by callmeVineeth** [comment]
I just seen you repo in a random GitHub issue search, and now successfully wasted my 2 days . Ok no issue, If there is any new upcoming open Source projects pls let me know.

**Comment by Anushka-Bhowmick** [comment]
> I just seen you repo in a random GitHub issue search, and now successfully wasted my 2 days . Ok no issue, If there is any new upcoming open Source projects pls let me know.

You were doing a great work indeed! So I thought of mentioning it on discord but since you are not a partcipant the core team won't accept the labels! You can still contribute just the labels won't be added.

**Comment by callmeVineeth** [comment]
Thank you so much for your support and guidance , I really appreciate it. Anyway  since I'm not an official participant I won't receive any recognition or certificates , so I don't want to participate it further. The learning experience was excellent.                 
 I've recently begun contributing to open source projects and am unfamiliar with the best platforms and upcoming events. Please keep me informed about any new events. 
I'm sending you a follow request on X platform so we can stay connected.

**Comment by Anushka-Bhowmick** [comment]
> Thank you so much for your support and guidance , I really appreciate it. Anyway  since I'm not an official participant I won't receive any recognition or certificates , so I don't want to participate it further. The learning experience was excellent.                 
>  I've recently begun contributing to open source projects and am unfamiliar with the best platforms and upcoming events. Please keep me informed about any new events. 
> I'm sending you a follow request on X platform so we can stay connected.
> 
> All the best. . . 
> 

Sure :)

**Pull request merged**
